version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_SECRET=n8n-secret-yt-uploader-2025
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - WEBHOOK_URL=https://roselle-dreamy-linus.ngrok-free.dev
    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  n8n-data:
